version: '2'

services:
  mssql:
    image: microsoft/mssql-server-linux
    container_name: mssql
    ports:
      - 1433:1433
    volumes:
      - "./app/nyom/:/temp/nyom/"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "nyom.7410"

  rabbit:
    image: rabbitmq
    container_name: rabbit
    ports:
      - 5672:5672